# Copyright 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
service: default
runtime: go116

entrypoint: >
  main
  -ts-mon-account app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
  -config-service-host luci-config.appspot.com

handlers:
- url: /.*
  script: auto
  secure: always

