application: findit-for-me-staging
version: 1
runtime: python38
app_engine_apis: true
service: default
entrypoint: gunicorn -t 0 -b :$PORT -w 8 default_main:default_application
instance_class: F4
automatic_scaling:
  min_idle_instances: 1
  max_concurrent_requests: 25

builtins:
  - remote_api: on

handlers:
# Static resources.
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /bower_components
  static_dir: third_party/bower_components
  secure: always

- url: /ui
  static_dir: ui
  secure: always

- url: /common.css
  static_files: static/common.css
  upload: static/common.css
  secure: always

- url: /js/flot/(.*\.js)$
  static_files: third_party/flot/\1
  upload: third_party/flot/.*\.js$
  secure: always

# icon
- url: /favicon.ico
  mime_type: image/x-icon
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always

# images
- url: /images
  static_dir: static/images
  secure: always
