runtime: go120

handlers:
- url: /.*
  script: auto
  secure: always

luci_gae_vars:
  chrome-resources-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
  chrome-resources-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}