# Copyright 2019 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

application: cr-buildbucket-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

# RPC Explorer.

- url: /rpcexplorer/?
  static_files: rpcexplorer/index.html
  upload: rpcexplorer/index.html
  secure: always

# The entire subpath is globbed because RPC Explorer uses native URL redirecting
# for sub-pages, and we want all of them to map to the same HTML file.
- url: /rpcexplorer/services/.*
  static_files: rpcexplorer/index.html
  upload: rpcexplorer/index.html
  secure: always

- url: /rpcexplorer
  static_dir: rpcexplorer
  secure: always

- url: /.*
  script: apps.frontend
  secure: always

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"

builtins:
- deferred: on
- remote_api: on

includes:
- components/auth
- components/ereporter2

skip_files:
- \.pyc
- ^(.*/)?.*\.(orig|rej|py[co])
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^tools.*
- ^[A-Z]+(\.[a-z]+)?
- .+\.md
- test
