service: default
runtime: python38
app_engine_apis: true
instance_class: B1
basic_scaling:
  max_instances: 3

entrypoint: gunicorn -b :$PORT --timeout 60 --workers 2 --threads 1 frontend.main:frontend_app

env_variables:
  NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: "True"
  MEMCACHE_USE_CROSS_COMPATIBLE_PROTOCOL: "True"

handlers:
# Static resources and home page.
# Web UI pages.
- url: /
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /robots.txt
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /common.css
  static_files: common/static/common.css
  upload: common/static/common.css

# PubSub push endpoint.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always
  login: admin

- url: /clusterfuzz/dashboard
  script: auto
  secure: always
  login: admin

- url: /cracas/public-dashboard
  script: auto
  secure: always
  login: required

- url: /uma-sampling-profiler/dashboard
  script: auto
  secure: always
  login: required

- url: /cracas/dashboard
  script: auto
  secure: always
  login: required

- url: /clusterfuzz/result-feedback
  script: auto
  secure: always
  login: required

- url: /uma-sampling-profiler/result-feedback
  script: auto
  secure: always
  login: required

- url: /cracas/result-feedback
  script: auto
  secure: always
  login: required

- url: /config
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto
  secure: always
