module: default
runtime: python27
api_version: 1
threadsafe: true
instance_class: B1
basic_scaling:
  max_instances: 3

builtins:
  - remote_api: on

handlers:
# Static resources and home page.
# Web UI pages.
- url: /
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /robots.txt
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /common.css
  static_files: common/static/common.css
  upload: common/static/common.css

# PubSub push endpoint.
- url: /_ah/push-handlers/.*
  script: frontend.main.frontend_app
  secure: always
  login: admin

- url: /.*
  script: frontend.main.frontend_app
  secure: always

includes:
- first_party/gae_ts_mon  # handles /internal/cron/ts_mon/send

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- __init__.py
- backend/.*
- scripts/.*

libraries:
- name: jinja2
  version: latest
- name: numpy
  version: 1.6.1
- name: flask
  version: 0.12
- name: grpcio
  version: 1.0.0
- name: setuptools
  version: 36.6.0
- name: ssl
  version: latest
