# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Creates author wise code coverage reports. Includes data only for
# lines of code which are modified in last N weeks, where N is controlled
# by recipe code. It works by joining latest code coverage data with
# blamelist data generated by recipe code.

from gae_libs.handlers.base_handler import BaseHandler, Permission
from services.code_coverage import author_coverage


class CreateAuthorCoverageMetrics(BaseHandler):
  PERMISSION_LEVEL = Permission.APP_SELF

  def _GetSourceBuilders(self):
    """Returns CI builders for which coverage metrics are to be generated."""
    return ['android-code-coverage', 'android-code-coverage_unit']

  def HandleGet(self):
    for builder in self._GetSourceBuilders():
      author_coverage.CreateAuthorCoverage(builder)
    return {'return_code': 200}
