cron:
- description: LUCI config datastore cache periodic refresh
  url: /admin/config/cache/manager
  schedule: every 10 minutes
- description: Device config data periodic refresh
  url: /internal/cron/sync-dev-config
  schedule: every 1 hours
- description: Manufacturing config data periodic refresh
  url: /internal/cron/sync-manufacturing-config
  schedule: every 1 hours
- description: Inventory change history periodic dump to bigquery
  url: /internal/cron/changehistory-to-bq
  schedule: every 10 minutes
- description: Push inventory to drone queen
  url: /internal/cron/push-to-drone-queen
  schedule: every 10 minutes

- description: Sync all devices to drone config
  url: /internal/cron/sync-device-list-to-drone-config
  schedule: every 24 hours

- description: Compare inventory from V1 and V2
  url: /internal/cron/compare-inventory
  schedule: every 24 hours

- description: report metrics of Duts in inventory.
  url: /internal/cron/report-inventory
  schedule: every 5 minutes

- description: Dump registered assets
  url: /internal/cron/dump-registered-assets-snapshot
  schedule: every day 00:00
  timezone: America/Los_Angeles

- description: Dump inventory snapshot
  url: /internal/cron/dump-inventory-snapshot
  schedule: every 24 hours
