#!/bin/bash

# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ./integration_tests

# die prints a message to stderr and exits abornmally.
die() {
  printf '%s\n' "$@" 1>&2; exit 1;
}

# main runs the integration tests.
main() {
  export CDPATH=
  readonly selfdir="$(dirname -- "$0")" || die 'cannot find self dir'
  cd -- "$selfdir" || die 'cannot chdir'

  readonly fleetcost="../fleetcost"

  test -f "$fleetcost" || die 'cannot find fleetcost binary'

  test_suite

  case "$?" in
    2) : "do nothing" ;;
    *) die "unexpected status $?"
  esac
}

test_suite() {
  "$fleetcost" ping -http                  || die 'test 1: ping'
  "$fleetcost" ping-ufs -http              || die 'test 2: ping-ufs'
  "$fleetcost" create-ci -http -name "some-name" || die 'test 3: create-ci'
  "$fleetcost" get-ci -http -name "some-name"    || die 'test 4: get-ci'
}

main "$@"
