runtime: go
api_version: go1
service: analyzer
instance_class: F4_1G

handlers:
- url: /_cron/analyze/.*
  script: _go_app
  secure: always
  login: admin

- url: /_ah/queue/.*
  script: _go_app
  secure: always
  login: admin

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
