plans:
    - name: cros
      criticalactions:
        - name: 'Set state: needs_deploy (''dut_set_state'') (RUN_ONCE)'
        - name: Check stable versions exist ('sample_pass')
          conditions:
            - name: Has a stable-version service ('has_stable_version_service_path') (RUN_ONCE)
          dependencies:
            - name: Recovery version has OS image path ('has_stable_version_cros_image')
              dependencies:
                - name: Has a stable-version service ('has_stable_version_service_path') (RUN_ONCE)
            - name: Check stable firmware version exists ('has_stable_version_fw_version')
              conditions:
                - name: Is a Chromebook ('dut_check_board') (RUN_ONCE)
                - name: Has a stable-version service ('has_stable_version_service_path') (RUN_ONCE)
        - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
          recoveries:
            - name: Power cycle DUT by RPM and wait ('sample_pass') (ALWAYS_RUN)
              conditions:
                - name: has_rpm_info
              dependencies:
                - name: rpm_power_cycle
                - name: Wait to be pingable (normal boot) ('cros_ping') (ALWAYS_RUN) (time:'2m30s')
        - name: DUT has expected dev firmware (for browser DUTs) ('cros_has_dev_signed_firmware') (time:'10m0s')
          conditions:
            - name: dut_is_not_browser_legacy_duts
          dependencies:
            - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
              recoveries:
                - name: Power cycle DUT by RPM and wait ('sample_pass') (ALWAYS_RUN)
                  conditions:
                    - name: has_rpm_info
                  dependencies:
                    - name: rpm_power_cycle
                    - name: Wait to be pingable (normal boot) ('cros_ping') (ALWAYS_RUN) (time:'2m30s')
          recoveries:
            - name: Update DUT firmware with factory mode and restart by host ('sample_pass') (ALWAYS_RUN)
              dependencies:
                - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
                - name: Collect HWID into inventory ('sample_pass') (RUN_ONCE)
                  dependencies:
                    - name: Read HWID from DUT ('cros_update_hwid_to_inventory') (ALWAYS_RUN)
                      conditions:
                        - name: Not Satlab device ('sample_fail')
                          conditions:
                            - name: Is Satlab device ('dut_regex_name_match')
                    - name: Read HWID from DUT (Satlab) (Allow to fail) ('cros_update_hwid_to_inventory') (ALWAYS_RUN)
                      conditions:
                        - name: Is Satlab device ('dut_regex_name_match')
                - name: Disable software-controlled write-protect for 'internal' (Allow to fail) ('cros_disable_fprom_write_protect') (ALWAYS_RUN) (time:'5m0s')
                  dependencies:
                    - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
                - name: Disable software-controlled write-protect for 'ec' (Allow to fail) ('cros_disable_fprom_write_protect') (ALWAYS_RUN) (time:'5m0s')
                  dependencies:
                    - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
                - name: Try to update FW from firmware image with factory mode (Allow to fail) ('cros_update_firmware_from_firmware_image') (ALWAYS_RUN) (time:'2h0m0s')
                  conditions:
                    - name: has_stable_version_fw_image
                - name: Try to update FW from OS image with factory mode (Allow to fail) ('cros_run_firmware_update') (ALWAYS_RUN) (time:'15m0s')
                  conditions:
                    - name: Missing stable fw image ('sample_fail')
                      conditions:
                        - name: has_stable_version_fw_image
                - name: Simple reboot ('cros_run_command') (ALWAYS_RUN)
                  dependencies:
                    - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'15s')
                - name: Wait to be SSHable (normal boot) ('cros_ssh') (ALWAYS_RUN) (time:'2m30s')
        - name: Update inventory info ('sample_pass')
          dependencies:
            - name: cros_ssh
            - name: cros_update_hwid_to_inventory
            - name: cros_update_serial_number_inventory
        - name: 'Set state: ready (''dut_set_state'') (RUN_ONCE)'
          dependencies:
            - name: All repair-requests resolved ('dut_has_no_repair_requests')
            - name: Reset DUT-state reason ('dut_reset_state_reason')
