plans:
    - name: cros
      criticalactions:
        - name: dut_state_needs_deploy
        - name: check_host_info ('sample_pass')
          dependencies:
            - name: dut_has_name
            - name: dut_has_board_name
            - name: dut_has_model_name
        - name: Collect logs (before) (Allow to fail) ('sample_pass') (RUN_ONCE)
          conditions:
            - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'30s')
            - name: Confirm log collection info does not exist (before) ('cros_confirm_file_not_exists')
          dependencies:
            - name: Create log collection info (before) ('cros_create_log_collection_info') (RUN_ONCE)
              conditions:
                - name: Confirm log collection info does not exist (before) ('cros_confirm_file_not_exists')
            - name: Copy messages (before) (Allow to fail) ('cros_copy_to_logs')
            - name: Copy eventlog.txt (before) (Allow to fail) ('cros_copy_to_logs')
            - name: Collect dmesg (before) (Allow to fail) ('cros_dmesg') (RUN_ONCE)
        - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'30s')
          recoveries:
            - name: Power cycle by RPM ('rpm_power_cycle') (ALWAYS_RUN)
              conditions:
                - name: has_rpm_info
        - name: Update inventory info ('sample_pass')
          dependencies:
            - name: cros_ssh
            - name: cros_update_hwid_to_inventory
            - name: cros_update_serial_number_inventory
        - name: Remove whitelabel_tag VPD field if necessary ('cros_run_command')
          conditions:
            - name: VPD cache has whitelabel_tag field ('cros_run_command')
        - name: Installed OS is stable ('cros_is_on_stable_version')
          conditions:
            - name: has_stable_version_cros_image
          recoveries:
            - name: Install stable OS ('cros_provision') (time:'1h0m0s')
              conditions:
                - name: has_stable_version_cros_image
                - name: cros_not_on_stable_version
            - name: Power cycle by RPM ('rpm_power_cycle') (ALWAYS_RUN)
              conditions:
                - name: has_rpm_info
        - name: Remove reboot requests from host (Allow to fail) ('cros_remove_all_reboot_request')
        - name: Update provisioned info ('cros_update_provision_info')
        - name: Validate RPM info ('rpm_audit_without_battery') (time:'15m0s')
          conditions:
            - name: has_rpm_info
          recoveries:
            - name: Power cycle by RPM ('rpm_power_cycle') (ALWAYS_RUN)
              conditions:
                - name: has_rpm_info
        - name: dut_state_ready
        - name: Collect logs (after) (Allow to fail) ('sample_pass') (RUN_ONCE)
          conditions:
            - name: Device is SSHable ('cros_ssh') (ALWAYS_RUN) (time:'30s')
            - name: Confirm log collection info does not exist (after) ('cros_confirm_file_not_exists')
          dependencies:
            - name: Create log collection info (after) ('cros_create_log_collection_info') (RUN_ONCE)
              conditions:
                - name: Confirm log collection info does not exist (after) ('cros_confirm_file_not_exists')
            - name: Copy messages (after) (Allow to fail) ('cros_copy_to_logs')
            - name: Copy eventlog.txt (after) (Allow to fail) ('cros_copy_to_logs')
            - name: Collect dmesg (after) (Allow to fail) ('cros_dmesg') (RUN_ONCE)
