runtime: go120

handlers:
- url: /prpc/.*
  secure: always
  script: auto

- url: /rpcexplorer/.*
  secure: always
  script: auto

- url: /auth/.*
  secure: always
  script: auto

- url: /internal/.*
  secure: always
  script: auto

- url: /(.*\.(png|css|js|txt))$
  static_files: static/\1
  upload: static/(.*)

- url: /(.*)
  static_files: static/index.html
  upload: static/index.html

luci_gae_vars:
  chrome-resources-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
