runtime: go121

handlers:
- url: /prpc/.*
  secure: always
  script: auto

- url: /rpcexplorer/.*
  secure: always
  script: auto

- url: /auth/.*
  secure: always
  script: auto

- url: /internal/.*
  secure: always
  script: auto

- url: /(.*\.(png|css|js|txt))$
  static_files: static/\1
  upload: static/(.*)

- url: /(.*)
  static_files: static/index.html
  upload: static/index.html

luci_gae_vars:
  chrome-test-health-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 961841358-3c87679tdm982jrrpebv04a31bl3ibgm.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://chrome-test-health-staging.appspot.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary
    FINDIT_CLOUD_PROJECT: findit-for-me-staging
  google.com:chrome-test-health-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 98610520980-rtgum5ggpvmenqap9i8es95vcedomlt0.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://chrome-test-health-staging.googleplex.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary
    FINDIT_CLOUD_PROJECT: findit-for-me-staging

entrypoint: >
  main
  -findit-cloud-project ${FINDIT_CLOUD_PROJECT}
  -auth-service-host ${AUTH_SERVICE_HOST}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-expose-state-endpoint
  -frontend-client-id ${OAUTH_CLIENT_ID}
