service: default
runtime: go116
app_engine_apis: true

handlers:
- url: /internal/.*
  script: auto
  secure: always
  login: admin
- url: /admin/.*
  script: auto
  secure: always
  login: admin
- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -ts-mon-account app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
