service: default
runtime: go121
app_engine_apis: true

handlers:
- url: /internal/.*
  script: auto
  secure: always
  login: admin
- url: /admin/.*
  script: auto
  secure: always
  login: admin
- url: /.*
  script: auto
  secure: always

luci_gae_vars:
  drone-queen-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
  drone-queen-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host config.luci.app
  -ts-mon-account app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
