service: default
runtime: go121
app_engine_apis: true

handlers:
 - url: /internal/.*
   script: auto
   secure: always
   login: admin

 - url: /_ah/push-handlers/.*
   script: auto
   secure: always
   login: admin

 - url: /src
   static_dir: ui/build/default/src/
   secure: always

 - url: /static
   static_dir: static
   secure: always

 - url: /node_modules
   static_dir: ui/build/default/node_modules/
   secure: always

 - url: /.*
   script: auto
   secure: always
