application: tricium-dev
module: default
runtime: go
api_version: go1

handlers:

- url: /internal/.*
  script: _go_app
  secure: always
  login: admin

- url: /_ah/push-handlers/.*
  script: _go_app
  secure: always
  login: admin

- url: /src
  static_dir: ui/build/default/src/
  secure: always

- url: /node_modules
  static_dir: ui/build/default/node_modules/
  secure: always

- url: /.*
  script: _go_app
  secure: always

skip_files:
  - ui/node_modules/
