// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: libs/cipkg_new/core/derivation.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Derivation is the atomic step transformed from different types of actions. It
// should contain all information used during the execution in its definition.
// NOTE: ${out} is not part of the derivation. We can't determine the output
// directory before we have a deterministic derivation so it has to be excluded
// from derivation to avoid self-reference.
type Derivation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Platform is where the command is executed.
	// This is used as "output only", and is used to disambiguate Derivation ID
	// for the same command runs on different platforms.
	// Actions will follow a convention w/ supporting library functions
	// in order to produce this consistently.
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Args are the `argv` vector of the derivation when executed.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Env includes all the environment variables for the execution isolated from
	// host.
	Env []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	// Inputs are ids of all packages referred by this derivation.
	// It depends on the package manager to interpret the ID.
	Inputs []string `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// fixed_output, if set, represents the content of the output. ID will be
	// generated based on fixed_output exclusively.
	// WARNING: Using fixed_output means shifting away the responsibility for
	// detecting any change from derivation. This should be rarely touched and
	// most of its use cases have a builtin implementation to take care of the
	// generated fixed_output value. Any use of it outside the builtin modules
	// are strongly discouraged. YOU HAVE BEEN WARNED.
	FixedOutput string `protobuf:"bytes,5,opt,name=fixed_output,json=fixedOutput,proto3" json:"fixed_output,omitempty"`
}

func (x *Derivation) Reset() {
	*x = Derivation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_cipkg_new_core_derivation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Derivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Derivation) ProtoMessage() {}

func (x *Derivation) ProtoReflect() protoreflect.Message {
	mi := &file_libs_cipkg_new_core_derivation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Derivation.ProtoReflect.Descriptor instead.
func (*Derivation) Descriptor() ([]byte, []int) {
	return file_libs_cipkg_new_core_derivation_proto_rawDescGZIP(), []int{0}
}

func (x *Derivation) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Derivation) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Derivation) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Derivation) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Derivation) GetFixedOutput() string {
	if x != nil {
		return x.FixedOutput
	}
	return ""
}

var File_libs_cipkg_new_core_derivation_proto protoreflect.FileDescriptor

var file_libs_cipkg_new_core_derivation_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x63, 0x69, 0x70, 0x6b, 0x67, 0x5f, 0x6e, 0x65, 0x77,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x65, 0x72, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x78, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x6c, 0x69, 0x62, 0x73,
	0x2f, 0x63, 0x69, 0x70, 0x6b, 0x67, 0x5f, 0x6e, 0x65, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libs_cipkg_new_core_derivation_proto_rawDescOnce sync.Once
	file_libs_cipkg_new_core_derivation_proto_rawDescData = file_libs_cipkg_new_core_derivation_proto_rawDesc
)

func file_libs_cipkg_new_core_derivation_proto_rawDescGZIP() []byte {
	file_libs_cipkg_new_core_derivation_proto_rawDescOnce.Do(func() {
		file_libs_cipkg_new_core_derivation_proto_rawDescData = protoimpl.X.CompressGZIP(file_libs_cipkg_new_core_derivation_proto_rawDescData)
	})
	return file_libs_cipkg_new_core_derivation_proto_rawDescData
}

var file_libs_cipkg_new_core_derivation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_libs_cipkg_new_core_derivation_proto_goTypes = []interface{}{
	(*Derivation)(nil), // 0: Derivation
}
var file_libs_cipkg_new_core_derivation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_cipkg_new_core_derivation_proto_init() }
func file_libs_cipkg_new_core_derivation_proto_init() {
	if File_libs_cipkg_new_core_derivation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libs_cipkg_new_core_derivation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Derivation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libs_cipkg_new_core_derivation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_cipkg_new_core_derivation_proto_goTypes,
		DependencyIndexes: file_libs_cipkg_new_core_derivation_proto_depIdxs,
		MessageInfos:      file_libs_cipkg_new_core_derivation_proto_msgTypes,
	}.Build()
	File_libs_cipkg_new_core_derivation_proto = out.File
	file_libs_cipkg_new_core_derivation_proto_rawDesc = nil
	file_libs_cipkg_new_core_derivation_proto_goTypes = nil
	file_libs_cipkg_new_core_derivation_proto_depIdxs = nil
}
