// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//go:build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"runtime"
	"slices"
	"sync"
	"time"

	"golang.org/x/sync/errgroup"
)

func main() {
	if _, err := exec.LookPath("go"); err != nil {
		log.Fatal("'go' command is not found, but it is required:", err)
	}
	if runtime.GOMAXPROCS(-1) < 16 {
		log.Fatal("please run on a machine with at least 16 cores")
	}
	shards := int(runtime.GOMAXPROCS(-1) / 16)

	for _, longtest := range []bool{false, true} {
		for _, race := range []bool{false, true} {
			log.Printf("Generating weights for longtest=%t race=%t", longtest, race)
			if err := generateWeights(shards, longtest, race); err != nil {
				log.Fatal(err)
			}
		}
	}
}

func generateWeights(shards int, longtest, race bool) error {
	tests, err := goDistTestList(longtest, race)
	if err != nil {
		return err
	}

	// Measure test run times.
	var eg errgroup.Group
	eg.SetLimit(shards)

	var testTimesMu sync.Mutex
	testTimes := make(map[string]time.Duration)
	for _, testName := range tests {
		testName := testName
		eg.Go(func() error {
			// Run the test.
			dt, err := goDistTestTime(testName, longtest, race)
			if err != nil {
				fmt.Printf("FAIL\t%s\t(%v)\n", testName, err)
				return err
			}
			fmt.Printf("ok\t%s\t%.3fs\n", testName, dt.Seconds())

			// Store the result.
			testTimesMu.Lock()
			defer testTimesMu.Unlock()
			testTimes[testName] = dt

			return nil
		})
	}

	// Wait for all tests to complete.
	if err := eg.Wait(); err != nil {
		return err
	}

	// Generate a Go file.
	contents := generateWeightsFile(testTimes, longtest, race)
	// Format it.
	formattedContents, err := format.Source(contents)
	if err != nil {
		return fmt.Errorf("formatting generated file: %v: contents:\n%s", err, contents)
	}
	// Write it.
	filename := "raw"
	if longtest {
		filename += "longtest"
	}
	if race {
		filename += "race"
	}
	filename += ".go"
	if err := os.WriteFile(filename, formattedContents, 0o644); err != nil {
		return err
	}
	return nil
}

func generateWeightsFile(testTimes map[string]time.Duration, longtest, race bool) []byte {
	var buf bytes.Buffer

	// Get a sorted list of all the tests.
	allTests := make([]string, 0, len(testTimes))
	for testName := range testTimes {
		allTests = append(allTests, testName)
	}
	slices.Sort(allTests)

	varName := "goDistTest"
	if longtest {
		varName += "Longtest"
	}
	if race {
		varName += "Race"
	}
	varName += "Weights"

	fmt.Fprintln(&buf, header)
	fmt.Fprintf(&buf, "var %s = map[string]int{\n", varName)
	for _, testName := range allTests {
		weight := int(testTimes[testName].Seconds())
		if weight <= 1 {
			// Unnamed tests have an implicit weight of 1.
			continue
		}
		fmt.Fprintf(&buf, "\t%q: %d,\n", testName, weight)
	}
	fmt.Fprintln(&buf, "}")
	return buf.Bytes()
}

const header = `// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by "go run computeweights.go". DO NOT EDIT.

package testweights
`

func goDistTestList(longtest, race bool) ([]string, error) {
	testListCmd := exec.Command("go", "tool", "dist", "test", "-list")
	testListCmd.Env = append(os.Environ(), fmt.Sprintf("GO_BUILDER_NAME=%s", goBuilderName(longtest, race)))
	if longtest {
		testListCmd.Env = append(testListCmd.Env, "GO_TEST_SHORT=0")
	}
	if race {
		testListCmd.Args = append(testListCmd.Args, "-race")
	}

	// Run the command.
	output, err := testListCmd.Output()
	if err != nil {
		return nil, fmt.Errorf("failed to run %q: %v", testListCmd.String(), err)
	}

	// Parse the output—each line is a test name.
	var tests []string
	scanner := bufio.NewScanner(bytes.NewReader(output))
	for scanner.Scan() {
		tests = append(tests, scanner.Text())
	}
	return tests, nil
}

func goDistTestTime(testName string, longtest, race bool) (time.Duration, error) {
	// Try to run three times, in case of flakiness.
	var dt time.Duration
	var testRunErr error
	for i := 0; i < 5; i++ {
		testRunCmd := exec.Command("go", "tool", "dist", "test")
		if race {
			testRunCmd.Args = append(testRunCmd.Args, "-race")
		}
		testRunCmd.Args = append(testRunCmd.Args, testName)

		// Always run with GOMAXPROCS=16. This is important for two reasons.
		// One, there are some tests that are only enabled if GOMAXPROCS is high
		// enough, so we don't want to miss them.
		// And two, most of our builder machines have 16 cores as of this writing,
		// so this will give slightly more accurate timings. It will still be slightly
		// wrong for other platforms, but we don't generally shard on those platforms.
		//
		// Set the test timeout scale high. We don't care that much, we just don't
		// want spurious failures here.
		testRunCmd.Env = append(os.Environ(),
			"GOMAXPROCS=16",
			"GO_TEST_TIMEOUT_SCALE=10",
			fmt.Sprintf("GO_BUILDER_NAME=%s", goBuilderName(longtest, race)),
		)
		if longtest {
			testRunCmd.Env = append(testRunCmd.Env, "GO_TEST_SHORT=0")
		}

		// Run the command, and time it.
		start := time.Now()
		if err := testRunCmd.Run(); err != nil {
			testRunErr = fmt.Errorf("failed to run %q: %v", testRunCmd.String(), err)
			continue
		}
		dt = time.Since(start)
		break
	}
	return dt, testRunErr
}

func goBuilderName(longtest, race bool) string {
	name := fmt.Sprintf("gotip-%s-%s", runtime.GOOS, runtime.GOARCH)
	if longtest {
		name += "-longtest"
	}
	if race {
		name += "-race"
	}
	return name
}
