service: default
runtime: go121
app_engine_apis: true

luci_gae_vars:
  cit-cli-metrics:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com

handlers:
- url: /(internal|admin)/.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -ts-mon-account ${TS_MON_ACCOUNT}
