# Copyright 2022 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cron:
- description: "Read configs from LUCI-config"
  url: /internal/cron/read-config
  schedule: every 10 minutes
- description: "Update analysis and create/update bugs for high-impact clusters"
  url: /internal/cron/update-analysis-and-bugs
  schedule: every 15 minutes synchronized
- description: "Sweeper job for transactional tasks."
  url: /internal/tasks/c/sweep
  schedule: every 1 minutes
- description: "Trigger ExportTestVariant jobs on a schedule."
  url: /internal/cron/export-test-variants
  # Note: to update the schedule, you also need to update
  # ScheduleTasks at weetbix/internal/services/testvariantbqexporter/task.go
  # to make sure the new schedule and time range of each row matches.
  schedule: every 1 hours from 00:00 to 23:00
  retry_parameters:
    # Do not retry after 55 minutes.
    job_age_limit: 55m
- description: "Purge test variants that have been consistently expected or no new results for over a month."
  url: /internal/cron/purge-test-variants
  schedule: every 60 minutes
- description: "Orchestrate re-clustering of test results."
  url: /internal/cron/reclustering
  # The actual reclustering interval is specified in the system config
  # as reclustering_interval_minutes. This just triggers the orchestrator.
  schedule: every 1 minutes synchronized
- description: "Global metrics reporting."
  url: /internal/cron/global-metrics
  schedule: every 10 minutes synchronized