# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/features.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/features.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJztWc9zE8kVZmakkdSW7PbYGCNgaQa8sKwtGbM27FYW1mAB3vgHJctkU7BxjaWRraykUTQjss'
    '4h91QlhyS33PJH5C/In5F7zsk9h7z3prs1s8aYyiGHVA4uT3/T/fq9r193f0/D/nSRXfUGnSr8'
    'HQyGQRRU274XjYZ+WKGmk+8F/WDodbrlcrpfM+jBq7hX+da7bRwEhz/3m5G05Q7Y5a1OGL0Ioi'
    '78C5+c7If+sO7/YuSHkbPIstHQa/rzhjDuTKzMVdTEFdmjgW/rcSdngWVGMHjepM7T486xyXad'
    'Xrs/ZuV3zRgOgn7oO0ssfyzfwKxW2pAcU9dd3F+x8nNf2dqLvOHTYNSP/jP/Kywn7coQZk/PDF'
    'GoTu6P2JV3zi0jucZYCOBBE1HyoFQvhKqb+1uDOThIW/4vuOzMsxx6MPRb8xb0z9dV0/2MzaS8'
    '+aAgVv5ssvwzmViOx5zTC+vcHHt0ZqKVb72/U+yMe8FpsZl3UO4khp+dDeWFc3rpWbbYRIIL5+'
    'p43OkFK187462y9vVfSyzPs/wCf8gN9ncjX6SGs/I3QzwNBifDztFxJFaW7z0UjWNfPD0eBr3O'
    'qCfWR9FxMAwrYr3bFdQpFMCyP3zrtypMADEiaIvouBOKMBgNm75oBi1fQPMoeOvDkorDE+GJJ3'
    'sbS2F00vWZ6HaaPrgEY7xINL2+OPRFG0JviU4fQF9sbT6t7ezVRLvTBeND4UVMHEfRIPyiWm35'
    'b/1uMPDBo6MgOOr6FThsqgD0l+Lpq9J8WD0MW4zl8ybP8Tzn8GjlL/ACtG7Ss8EZPC+xYt4GvA'
    'hccCCGWvCuSGMmqWXC+xI3+RvGVRt6lLjN5xOICUiZ308gFiCP+DfaisEnwcqB7mEQYvPLCcQE'
    '5ApfTSAWIF/x19qKyafAynPdA+1OgZXpBIJ9ZvhCArEAWeZP2UI+A9HMQrSXuFG+JHb87yPhvY'
    'W08Q6B7cg7+kLcZ0BDhoKcBRpuwNQZScNFmPoyc1Q7nyFkFijlGrMJm0wgBiBTfDaBWIBcAvqU'
    'ZYPPwZgZbdkAy4hcJHIUZhNWSCA4jiXmQrrm+DR3KFADqLzAr50Z6EocqEEd89wldwwK9CpMJM'
    'isIQNFhCUQG5AJmGiMGIDM8CsJxALkI36dnDH5DXDm1nmsIxc3tDMmOeNq1k3pDCI3+C2aypTu'
    'uJp1U7rjatZN6Y6rWY8T52bKMrKOiCtZNyXriBUTCI4rJSwj6zfJMgZq8TsQ6N3zWMcdeAcCvU'
    'nuWBToJzDRPLljyUARuUOZrLAsYfkEYgBSgOQZIxYgc/wSuZPhFXBn5Ux3PovdwWypgDtlcidD'
    '7lQ1OxnpDiIVfpWmykjeq5r3jHSnqnnPSHeqmvd4hZdTlpF3RKqS94zkfVnznpG8L2veM5L35Z'
    'Rlk9/T+yhemwwhywnLJlCImJ1ADEByiSjwwLin91GWr8X3xvtXNAtm1oDCK+ROlih8oFc0KylE'
    'ZI1fo6myckUf6BXNSgof6BXNSgof4Ioe2iQX77N/3mLvEZ1jaer+mhWTisWZBWETfOf3SUQU6n'
    'HDmWP20PfCoE/6pVCXLdQdw3j0QSfWKoV6QSKbLecGK0b4zmvGwiRDHSYQW48hd50VnwY9uIR9'
    'vNvbjsMyAy86ltPTM87SCQ9a/rADlyp5kK8XOuFGDLh/MEDddPxuC8dfZvk2PqM/aCNTz1EbvA'
    'Ez8au+1/NlIAVCdgBwbrNMdDLwKYrJlZmxXiDbDXhVpw7OTVbyBsDjW68bm4rDKioQrbmPWX7L'
    'O/S76BNw2sVnxSk1zovKYwUQKtEoRAvAf0gNaUK20EbP9/pQLcANr2wQsgvAD6awfjjFC5bfDM'
    'ORjzPAUoH3WHLEMcXzTEiMCAJqu0ETgu7E7pbqOWpvttwWy8nqwbnEclg/jPm3sRknQ6sTDrre'
    'SXIBJiRGM5zj7yZjY7WMmZLwlJ5hDbPBL/vvK27i93d/b7CCXldnguV2dg8aP31Z4xecEivUdv'
    'a346bhFIGknUbcMrG116jHLQu77u/VZDODzY31Ri1uZrH5ZHd3K27aOHS/Lls5Z5qV1l++rO++'
    'WpdQ/uu/XAMFikLrZyC0/mWBAi3+7yvQlT+aEA44Q7ZafrvT98HRngfB0Fl1OGqHsSfeELzuN7'
    'ujFvjshWLgDSHUoM1Eb9SNOgMYj1GD9RCdupsuocXLJ2GFMeFCFrhCvgIq+pEHUfn9YHR0DObb'
    'wbDnRZ2gDxFDYGJ/U8BYmaQMGOz5QGX/CFGkApN7UXjITQuOsE77BF+iHegb+43dmt0OvEUymZ'
    'Dno+gFFBD0bMNSUjdatWEl1uWTpLFjRepAJpTPvGBWx4rUgUGzbFkr0hm871whvtmrPxN0mI9n'
    'e9HY3gIWj3yYMKlZcYzD5xJ6NEtYPqVZZ+AKmkxp1hm6EWtas86i9nVXxe4ACfW6OvLBaDgIIM'
    'HIE0kN0t3yD0dHR0BgwiG8/NHQjLzvYixLWD4ldWfBoamU1J2FMGbYE4mYJLzn3ZWxQ/HcS+Fo'
    'MICnlgijIS4f+gLLCddS5PebJwlvTC3px3IdBcPFlDcmSfpCwmOTJD1qrs8lYpFYL7ufiFrlqL'
    'IobuOt+JX/vdcbxHvmNu422E0HOimUE5ZW//N6AgucmEs5YZH6L/CLCQQnnQetE6v/jyCpbpwn'
    'uA3qiEk1Vv/XMUHIHaX+EflIpowhU+a6dkfp/+vgTiml/69DVTmtLRtcwJg5bRnXHpHriToC11'
    '5oeWbItRcgz6YTiAXILIS+AProAl/gKFbPCvRzDDRLDi5A0T8J7mTl7vlYateszvqPZYWlEBOQ'
    'IgSlxhj8NvTguochkYkEYgIyCamqxqCENyl1szp97shySiHYp5TwzSKZPx5jkcxPjgGpD0hyTA'
    'aqjqRvmAN3U75hGXY35VuWf5oagyL209QYEKCAJMfYfDE1xoYxi6kxNoxZTI3J8aVUPDkYs5SK'
    'JwdjllLx5KHWMGkjyjbVKEkreIxW6BCIS8z7kAifn3eMIv336ez9RpeYq5iX5Reisbuxe6c5hG'
    'OKrjUlL6qfLa+tfPKF2Aj6tyO8EwTpSrG5EeJFoa6GGA3lVlbFKtq+LzPclHtnVe8dVayuwt6Z'
    'ThWrq5Th42J1TdcSqlhFZFXuSlPunbWUZYPGqZNKFatrdFIpyybVHxe1ZVNXKfN6FC76A7nECs'
    'EqpUhpoBCsUmbkSRK3H8KYK9oyHmyIPJCHlikPtocpnzHVH4LPcwkELV2G4jQusL+EZf7qvIMN'
    'zXwpf8ZSBfYjXR2qAhuRL+XiqAL70akC+5G+C1WB/YjuQmXZ4I/1wWbJxUHkUaIsx8V5rA82Sy'
    '7OY32wWXJxHsuDDUv3DQj0xYeU7hsQ6HSidK/RxkmW7ohsSHcyMtCaDlSV7jV9x6rSvUbba1y6'
    'P9OBqtIdkVqqLM8SZicQHKcCVaX7M53fcen+PGUZsxCRZzIPVOn+/FTp/jxlGbPuuaYwy7eAwt'
    '3zcgVPvS2dK3Hpvo3Xd6p0R2RL5ooq3bdPle7b+k5Wpfs23cnKssF3dKBZSSEi2zAb11iWsHwC'
    'wXHqiMhKCnd0oDbfg0B/cl6u4FG9B4FOkTs2BdrQu9+WgSKyJ6eyZaAN7Y4tA22AOzyBWIDg7l'
    '+XiMH3SQHdE34PfFlE0R4chs0R1iTdzne+cFFd9yuVSlIXufL4tCU3aKQhGbUlN/spZwyaqpDq'
    'YwGiWLcpvV5p1m2ZXojsS9ZtmV6vdHrZMr1e6fSyZXq90qzn+Ou4nnt/euFl9xpYjw+MHLH+Rm'
    'usnGQdkddyH+Uk6290oDnJ+hutsXKS9TdaY+XI4W/13s9JChF5IxM3xmzCCgkExzG593OSwm9x'
    '7+vfnP5hsw/6mPlhH0bd3xgsp77tVFiB6vaDod+Wn9zeUdvnqU/ytwEz8dsAflQb9Xre8ET+UK'
    'WajmATLT9sDjtUFqhfqRLQ17/Lyo9D/P8fh6jS5BP6g1Bcd07oQyNWzkUtRlRViciE3CnqS0gx'
    '9b0i/rDEEmUTpm9Ri5FYX5f0xlDlISLFRC2EJ0DpVHlY0htDlYclvTFiFT6pDzpV6iFSkhtDlX'
    'qTp0q9SX3QqVJvUsucWKtPpb4LocxBZDJVm2UJS9dvU2B5NoGgpUt8Xm25fwObBJ51')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


FeaturesServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/features.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/features.proto']['services'][u'Features'],
}
