# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/users.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/users.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJzlWktTHMkRVndPz/QUMBTNU2i1ao2EHggNEiySkGMlIQESGzwUA8jrkNZEM9PA7A7T4+kerb'
    'n46rPtCP8JX+2/4R9gR/jok3+AI+yDM7MeUw2SsDfCF/ugiKmvK7Mys7Kysj7E/niFXQzbjVn4'
    't9fuxGk8202iTlKh3753HLfiTthoTgZnJ+3F+99GtVTOnZzMzqjFxyAsvpUXWG4XJPwR5kbHoG'
    '7CCqxbxaoY+OOsQPoa9QkbcKeax+FavbzPJtcbSVqNDqJO1KpFdVSSVKOfdaMk9WeYm3bCWkTK'
    '+ubGKsrYipyxg1+rYpI/xvK0WgJrOLC2HJVfsEsfXCNpx60k8q8zlwICiziwSKm3CM6rio/l31'
    'ls9GWUIvQC/G6kP9BIHR/bjM8UKx104uO9tHEMAuFxe8KBz4XqAKI7CvRvssFuK200jXk5mlci'
    'WE8sb7Cx08ZKb+dZP+1ETeDSad4zWghU+7o94XKXjUt122kIKKz2w7yfYR6t3okOKAB9c0Onwh'
    '0dVClV4Ed5kU2cXVb6cZkxcBX9AJQWH6gWEzWt/EuLDaKQ0PlfN9WfYAVcvBPVaee8qhqW7zPe'
    'M+TfMn7utw5zKUf9CivICPhnV588larlC36dDX8g1f3rvYkfP22TU+fMEsbDKruslM0u/0pP9I'
    'OHZDL4+ASt9i3jp7fbv3pG7nQGTpY/NUUrf8E8tQ3+xZ7EqRyZnPzQJ6Xkq3+MMI+7/ALf4hb7'
    'q+X108Cf+7MVvIjbJ53G4VEazN27/yjYOYqCF0dweBvd42Cpmx7FUHGDpWYzoElJ0IlA9fuoXm'
    'EBLBLEB0F61EiCJO52alFQi+tRAMPD+D3sQT3YPwnC4Pn28t0kPWlGLGg2ahGYBDJhGtTCVrAf'
    'BQfgcT1otACMgvW1Fyub2yvBQaMJyjtBmLLgKE3byePZ2Xr0PmrGbbwDDuP4sBlVoBjMAtC6K5'
    'afleqT2f2kzpjn2bzAPc7hp+Nd4EUY3abfFmfw+xrr9/KA92MsIDA0gm/9IDPASjSy4fsAt0GO'
    'qzHMGOB5mNFDbEAG+ZiBOIBc5VNai8VLoGVPz7AIyfOLBmIDcokvGIgDyDP+VmuxYRWbv9YzUO'
    '8gaBkxEJwzxu8YiAPIA76utTicg5Y3egbGg4OWMQOxAZngswaCUo95VWvJ8SHQ8kTPyIGWIdBS'
    'MhAbEM6vGIgDyDR/zDrw+wIfh8hPcmuyHuxsLW/d+jb+9vuwdXj7caCS+fH9h/fuz2A2NDHdOs'
    'H3jfQoCGHUaB3EQSuqRUkSdk4giTosqHWiMG20DiHnsL4FcMNTHrXDw6jCYH9ztHvjsL/94EdO'
    '7u8E+DHMfDUGzxAZJ08U5hLmGYgFSDEzxwFkiPtas8UvgsyI1myBZkQmYDWuMZewgoGgnMcHDc'
    'QBxAepKYry5xC1qxC18WAz+nkahO8hUOE++JmGh4+DeeGoRRM9XiZzLHL0Cix0kcyxpKOIfM6v'
    '01ICyxNWMhALkEFKMYU4gIzzCa3Z4gHIXNYz0FFEmIG4gPTxIQNBKR+09BAHkEv8M7Lf5tfBzR'
    't0LHO0xnXw5hqtaZM3U7DCJEnb0pspvaYtfZmCNQcNxAKE81EDcQCZgKhMUXJOw5qzHw3tFyK0'
    'eF6mwZjLZIxDxtzRoXWkMYhMU+4rLE9YyUAsQFRoHWnOHR1ah9ye0dnpyNAicocqh8JcwjwDQb'
    'misRYGd0Znp0N14i5tmtKMJxqRGZmdAnMJKxqIBQiT2+bI+nKXtk1pdngF00prdkAzIndligjM'
    'JaxoIBYgzPDLIU2fgRRGPcfnYHO+kAmB52AO9uBzWjVHezAP+q6RdE7uwbxOiJzcgXmdhDm5A/'
    'OQhJ8biAPIVTg2mBAufwRr/ui8s+aCmkdgzBUyxiVjFnVCuNIYRB7xq7SUK81Z1AnhSnMWdUK4'
    '0pxFnRAuhf8xFietGRMCkUUZOIHlCSsaCMox2P4e4gAyCkUfHc3zp+Do0kcdnROO5kHNU3A0IH'
    'Py5OgzrGhkTl46ishTiCDXmEuYZyAWIEWZaXnp6DO4t8bJnAJfAXPWzjuIBVCzAuaMkzkFMmdV'
    'x70gzUFkRUanIOO+quNekOas6rgXpDmrOu4FivtLHfeCjDsiq4ZmjPtLHfeCjPtLHfeCjPtLir'
    'vSbPNX+ogX5EFE5CWsxjXmEpY3EAuQguEFHrxXdMQxhB7fEP3ep3fUAzUbEELhqEch3NQ76skQ'
    'IrIhi60nd3RT76gnQ7ipd9STIdzEHd3P00t7nv3JY+e+1Xvv+vLvLZYXzTa+O8S7by85CuULvS'
    'iQ7aPQv8SKIbWqvXe6J4C1un+F9UlZfHzK96lUhw9PfMPKCcfYTBxG9DYtVgcEuiFA/wYblNM6'
    'UTve63aaE645rwrobqf51d/y0Gt7EPthKFV/sb1+GvyP99pz78EbsIVU1aODRitKAtrQ/e5Bgt'
    '0ZWJrASyUIYf1O1AxTtLib4MSEBTIHZoKocljBfi9q1oP3YRMkZgKMb9TCrygcpmlYOyKgInp8'
    'Rj3+FHWUAyLwH0n6B70mcACESkYTWNJJr5pARAY4zzSBpTNNYEknvWoCS1TGek0gtuxjmSYQkZ'
    'K8QlUTOHimCRwEC4cyTSBUKOhdlGab2vhJrRnrBiLiIaIwl7CigWCzz2QPpB4InHogpdmh1v4z'
    'rdmRzT6XJeCCvMCHMtFw6AFQlFVLPRqGoMG/pDXn4LJVTYd4EAhkCFbjGnMJ8wzEAqRoRAx7NR'
    '+bDl1c/n6dfYLmM8rKL1i/SZsgsZXG30UtRfzRADk5eEwkcUvyXXKElagjpLHWOKISSQSKzVXW'
    'n+K3sCYoElFJ+hBbElB5ifVDVYOXeYTv/APfZ7l2mB7J5ek3rtJI9upRpwGnnyzwqsVGsiyA8q'
    '8t5q3iEUH5i8yj44L2oI5ctUBjsAbUiE+tECqfcKRIyCYA/k2WS0/aoiSW5oZ7DALp3oFPVZrg'
    'X2MDYRviCAdSqBJu9SsQtZWfMm893I+aaBPEtIm/VUxpcJ5XIStup2HaTVADxD+hgVQhR6jjOA'
    'pbyR6WIqWDkC0ATi3hnF7iFfPWsAzhCrBVYD2WHeGTWKdPYhQgCG0zroHT8loZqBZovFYv11lB'
    'slkmRyziLzliXKHeSNrN8MTcgD6J0Qrn2PuasVdx2hSkFmaKYSn99iusGH/fOo/u82gO/Jr+lc'
    'WKenv9PlbY3Nrb+clraLf8AVZc2dzdEEPL74dYbe6IkY2j7Z2qGDk4dXd7RQ5zOFxe2lkRQxeH'
    'z7e21sUwj6K7VTkq+ENsYOn16+rWmyUJeV/94TLcmEjC/BRuzH86cGP2/x/cmL+xP3BlJsfIbf'
    'QuTrIk7IDVrVqzWwebQ7hXww64Gh+w4LjbTBttkEevQXuCRk1nO6rg9XO8KIMyMtPqooVQtNIQ'
    'vIpacffwiNiUznGYNuIWXdZhsLsWgKzMVQYRPI4glK1DRDEUmOPiQm7UoZI1Dk7wI7EySSzsxm'
    'm1ZgO+YjBZIMtkcByTQzAT/0pA02jXOvI+Lxn3uS8Zog/f5wu9+9wHoRF2T9/nw9hTl4Pg6+3q'
    'akA1vbfaq52NdUUKmTc+yvjG7Yk3/vCZG3/4DO0zTF33ir7xR5D2KS8EW20MaNjUnre7nXYMCU'
    'aWyNBguOvRfvfwEAJoGISNAioaPsUWjWQMsmi54im2aITYoue6URjF5qY81zNIrH036bbb8Kse'
    'JGkHt4/6tHoEt1MatWonhjV4daOWEflIUs3FaMYadH400xBhMzFKDdGibi7GsG0p3w5WqNe7iZ'
    'fjs+jn4XFbnJmbeNrgNO3ppDD7EBQeNToB7EPGzvQhY2DEaKYPGdMsz39IoI2cItD8DxBoYwY5'
    '5hLmnSLQisQXmwQah+YuS6CNac2KQLsiH449Ck09AXsUWiFDqiGFhk3iFDzykSL7FJ21iI66kh'
    'VzqRt25em5Id/Hrs76G7KLVIgNSD/R5K7M+pvYIeoZlkT6DMQGpASpqmRsfgv7VT0DtdySlI1C'
    'cM6AYZvDb2dkcLdvZ2SQvL6dkcnx6YxtOSLwTNuQb5zO2OYSWdeTcYmsM2VcD2k4UyZPNFxPJi'
    '/puz4DQYLNlCkQwdbzp0AEm+lPgag60x+PqLMRPcMj6szUgmW0oiljm89zZKTOKaM2sWFYe7/2'
    'FMm6gHk5+Urw87UOlCm61lSHMfvFvQdztx8Hy3HrZop3gny6rS0neFGoq0GgiTzKiq5F3fMyw2'
    '15dhb02VGE7QKcnaEMYbugn0EiZR7op5stzw4iC/JU2vLsPMhotkhOVSpbnp0H+ukmUu8hFhut'
    'GRMJkQey/AgsT1ifgViA9MuHoy1r4EOo4yNas8MfgcwlrRkLGyIPDWraIfbRtNkhmrFo+OWQpo'
    'vwLBP09Zcc+bhzChuq+ZK2uUdfP8mQzLg5iHwpN8eRm/MkQzLj5jzJkMy4OU8yJDPShaqwKfoa'
    'kScGyYyb81QXNkVfP9WFTdHXT2VhwzfjMjj66jx6EI/5Mj2iexzxiv6LjOKIEVmW5uSkoyvaUc'
    'USr+g7VrHEK3S8lGaLKMUxrdnSxOOIlkJHV7WjOenoqnY0Jx1d1flNu0yUYk+zrYnHMS2F5epl'
    'RrMgLE3NNhGPKoQuX/8kPWgw2+s6VwSzvaFZB8VsI7JucMsYwg0dQsVsb+g7WTHbG5p1EMz2pn'
    'ZUMdsm8ejKEG5mNFuSeBzKMNub2tE83wZHf3xermCp3qa/uvWY7R19+hWzjci2XEox2ztnmO0d'
    'MIdnmO0dOv1LErH4LnVA9wP6TzQz2LTH+0mti2+SZuO7KChjd92qVCpmX1SW5TMvY4NKdmRE8z'
    'I2uxljLFqqmJnjAKKinqf0eqOjnpfphciujHpeptcbnV55mV5vdHrlZXq90VEv8LfiPffp9MLL'
    '7i1E3TcI/He6x1IEPiJvM+S8S5iXIfDf6R5LEfjvdI8lCPxv9D2hCHxE3mXI+TxhWQL/G9jM4Q'
    'yB/43Ja/8LI++b1A==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


UsersServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/users.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/users.proto']['services'][u'Users'],
}
