// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: infra/cros/cmd/cros-tool-runner/api/templates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Container:
	//	*Template_CrosDut
	//	*Template_CrosProvision
	//	*Template_CrosTest
	Container isTemplate_Container `protobuf_oneof:"container"`
}

func (x *Template) Reset() {
	*x = Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescGZIP(), []int{0}
}

func (m *Template) GetContainer() isTemplate_Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (x *Template) GetCrosDut() *CrosDutTemplate {
	if x, ok := x.GetContainer().(*Template_CrosDut); ok {
		return x.CrosDut
	}
	return nil
}

func (x *Template) GetCrosProvision() *CrosProvisionTemplate {
	if x, ok := x.GetContainer().(*Template_CrosProvision); ok {
		return x.CrosProvision
	}
	return nil
}

func (x *Template) GetCrosTest() *CrosTestTemplate {
	if x, ok := x.GetContainer().(*Template_CrosTest); ok {
		return x.CrosTest
	}
	return nil
}

type isTemplate_Container interface {
	isTemplate_Container()
}

type Template_CrosDut struct {
	CrosDut *CrosDutTemplate `protobuf:"bytes,1,opt,name=cros_dut,json=crosDut,proto3,oneof"`
}

type Template_CrosProvision struct {
	CrosProvision *CrosProvisionTemplate `protobuf:"bytes,2,opt,name=cros_provision,json=crosProvision,proto3,oneof"`
}

type Template_CrosTest struct {
	CrosTest *CrosTestTemplate `protobuf:"bytes,3,opt,name=cros_test,json=crosTest,proto3,oneof"`
}

func (*Template_CrosDut) isTemplate_Container() {}

func (*Template_CrosProvision) isTemplate_Container() {}

func (*Template_CrosTest) isTemplate_Container() {}

type CrosDutTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CrosDutTemplate) Reset() {
	*x = CrosDutTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrosDutTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrosDutTemplate) ProtoMessage() {}

func (x *CrosDutTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrosDutTemplate.ProtoReflect.Descriptor instead.
func (*CrosDutTemplate) Descriptor() ([]byte, []int) {
	return file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescGZIP(), []int{1}
}

type CrosProvisionTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CrosProvisionTemplate) Reset() {
	*x = CrosProvisionTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrosProvisionTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrosProvisionTemplate) ProtoMessage() {}

func (x *CrosProvisionTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrosProvisionTemplate.ProtoReflect.Descriptor instead.
func (*CrosProvisionTemplate) Descriptor() ([]byte, []int) {
	return file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescGZIP(), []int{2}
}

type CrosTestTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CrosTestTemplate) Reset() {
	*x = CrosTestTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrosTestTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrosTestTemplate) ProtoMessage() {}

func (x *CrosTestTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrosTestTemplate.ProtoReflect.Descriptor instead.
func (*CrosTestTemplate) Descriptor() ([]byte, []int) {
	return file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescGZIP(), []int{3}
}

var File_infra_cros_cmd_cros_tool_runner_api_templates_proto protoreflect.FileDescriptor

var file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDesc = []byte{
	0x0a, 0x33, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x63, 0x6d, 0x64,
	0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x2d, 0x72, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x74, 0x72, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x22, 0xd7, 0x01, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a,
	0x08, 0x63, 0x72, 0x6f, 0x73, 0x5f, 0x64, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x63, 0x74, 0x72, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x6f, 0x73,
	0x44, 0x75, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x72, 0x6f, 0x73, 0x44, 0x75, 0x74, 0x12, 0x49, 0x0a, 0x0e, 0x63, 0x72, 0x6f, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x74, 0x72, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0d, 0x63, 0x72, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x3a, 0x0a, 0x09, 0x63, 0x72, 0x6f, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x74, 0x72, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x72, 0x6f, 0x73, 0x54, 0x65, 0x73, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x72, 0x6f, 0x73, 0x54, 0x65, 0x73, 0x74, 0x42, 0x0b, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72,
	0x6f, 0x73, 0x44, 0x75, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x17, 0x0a,
	0x15, 0x43, 0x72, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x6f, 0x73, 0x54, 0x65,
	0x73, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x69, 0x6e,
	0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x72, 0x6f,
	0x73, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x2d, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescOnce sync.Once
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescData = file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDesc
)

func file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescGZIP() []byte {
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescOnce.Do(func() {
		file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescData)
	})
	return file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDescData
}

var file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_infra_cros_cmd_cros_tool_runner_api_templates_proto_goTypes = []interface{}{
	(*Template)(nil),              // 0: ctrv2.api.Template
	(*CrosDutTemplate)(nil),       // 1: ctrv2.api.CrosDutTemplate
	(*CrosProvisionTemplate)(nil), // 2: ctrv2.api.CrosProvisionTemplate
	(*CrosTestTemplate)(nil),      // 3: ctrv2.api.CrosTestTemplate
}
var file_infra_cros_cmd_cros_tool_runner_api_templates_proto_depIdxs = []int32{
	1, // 0: ctrv2.api.Template.cros_dut:type_name -> ctrv2.api.CrosDutTemplate
	2, // 1: ctrv2.api.Template.cros_provision:type_name -> ctrv2.api.CrosProvisionTemplate
	3, // 2: ctrv2.api.Template.cros_test:type_name -> ctrv2.api.CrosTestTemplate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_infra_cros_cmd_cros_tool_runner_api_templates_proto_init() }
func file_infra_cros_cmd_cros_tool_runner_api_templates_proto_init() {
	if File_infra_cros_cmd_cros_tool_runner_api_templates_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrosDutTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrosProvisionTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrosTestTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Template_CrosDut)(nil),
		(*Template_CrosProvision)(nil),
		(*Template_CrosTest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_cros_cmd_cros_tool_runner_api_templates_proto_goTypes,
		DependencyIndexes: file_infra_cros_cmd_cros_tool_runner_api_templates_proto_depIdxs,
		MessageInfos:      file_infra_cros_cmd_cros_tool_runner_api_templates_proto_msgTypes,
	}.Build()
	File_infra_cros_cmd_cros_tool_runner_api_templates_proto = out.File
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_rawDesc = nil
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_goTypes = nil
	file_infra_cros_cmd_cros_tool_runner_api_templates_proto_depIdxs = nil
}
