// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/qscheduler-swarming/app/state/proto/state.proto

package proto

import (
	fmt "fmt"
	protos "infra/qscheduler/qslib/protos"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QSchedulerPoolState struct {
	Scheduler            *protos.Scheduler  `protobuf:"bytes,1,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	Reconciler           *protos.Reconciler `protobuf:"bytes,2,opt,name=reconciler,proto3" json:"reconciler,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QSchedulerPoolState) Reset()         { *m = QSchedulerPoolState{} }
func (m *QSchedulerPoolState) String() string { return proto.CompactTextString(m) }
func (*QSchedulerPoolState) ProtoMessage()    {}
func (*QSchedulerPoolState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6979371fea009f3, []int{0}
}

func (m *QSchedulerPoolState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QSchedulerPoolState.Unmarshal(m, b)
}
func (m *QSchedulerPoolState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QSchedulerPoolState.Marshal(b, m, deterministic)
}
func (m *QSchedulerPoolState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QSchedulerPoolState.Merge(m, src)
}
func (m *QSchedulerPoolState) XXX_Size() int {
	return xxx_messageInfo_QSchedulerPoolState.Size(m)
}
func (m *QSchedulerPoolState) XXX_DiscardUnknown() {
	xxx_messageInfo_QSchedulerPoolState.DiscardUnknown(m)
}

var xxx_messageInfo_QSchedulerPoolState proto.InternalMessageInfo

func (m *QSchedulerPoolState) GetScheduler() *protos.Scheduler {
	if m != nil {
		return m.Scheduler
	}
	return nil
}

func (m *QSchedulerPoolState) GetReconciler() *protos.Reconciler {
	if m != nil {
		return m.Reconciler
	}
	return nil
}

func init() {
	proto.RegisterType((*QSchedulerPoolState)(nil), "proto.QSchedulerPoolState")
}

func init() {
	proto.RegisterFile("infra/appengine/qscheduler-swarming/app/state/proto/state.proto", fileDescriptor_d6979371fea009f3)
}

var fileDescriptor_d6979371fea009f3 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0xcf, 0xcc, 0x4b, 0x2b,
	0x4a, 0xd4, 0x4f, 0x2c, 0x28, 0x48, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0x2f, 0x2c, 0x4e, 0xce,
	0x48, 0x4d, 0x29, 0xcd, 0x49, 0x2d, 0xd2, 0x2d, 0x2e, 0x4f, 0x2c, 0xca, 0xcd, 0xcc, 0x4b, 0x07,
	0xc9, 0xea, 0x17, 0x97, 0x24, 0x96, 0xa4, 0xea, 0x17, 0x14, 0xe5, 0x97, 0xe4, 0x43, 0xd8, 0x7a,
	0x60, 0xb6, 0x10, 0x2b, 0x98, 0x92, 0xd2, 0x85, 0x98, 0x83, 0xd0, 0xad, 0x5f, 0x58, 0x9c, 0x93,
	0x99, 0x04, 0xd1, 0x50, 0xac, 0x0f, 0x17, 0x86, 0xe8, 0x92, 0xd2, 0xc3, 0xaf, 0xbc, 0x28, 0x35,
	0x39, 0x3f, 0x2f, 0x39, 0x13, 0xae, 0x5e, 0xa9, 0x8a, 0x4b, 0x38, 0x30, 0x18, 0xa6, 0x36, 0x20,
	0x3f, 0x3f, 0x27, 0x18, 0xe4, 0x04, 0x21, 0x7d, 0x2e, 0x4e, 0xb8, 0x09, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0x82, 0x10, 0x1d, 0xc5, 0x7a, 0x70, 0xe5, 0x41, 0x08, 0x35, 0x42, 0x46, 0x5c,
	0x5c, 0x08, 0xb3, 0x25, 0x98, 0xc0, 0x3a, 0x84, 0x60, 0x3a, 0x82, 0xe0, 0x32, 0x41, 0x48, 0xaa,
	0x92, 0xd8, 0xc0, 0xd2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x17, 0x40, 0x84, 0x2b,
	0x01, 0x00, 0x00,
}
