// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/libs/fleet/protos/asset.proto

package fleet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next Tag: 3
type ChopsAsset struct {
	// Asset's state and location
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChopsAsset) Reset()         { *m = ChopsAsset{} }
func (m *ChopsAsset) String() string { return proto.CompactTextString(m) }
func (*ChopsAsset) ProtoMessage()    {}
func (*ChopsAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbeede6b2764bfe, []int{0}
}

func (m *ChopsAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChopsAsset.Unmarshal(m, b)
}
func (m *ChopsAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChopsAsset.Marshal(b, m, deterministic)
}
func (m *ChopsAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChopsAsset.Merge(m, src)
}
func (m *ChopsAsset) XXX_Size() int {
	return xxx_messageInfo_ChopsAsset.Size(m)
}
func (m *ChopsAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_ChopsAsset.DiscardUnknown(m)
}

var xxx_messageInfo_ChopsAsset proto.InternalMessageInfo

func (m *ChopsAsset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChopsAsset) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

// Next Tag: 8
type Location struct {
	// Location of the asset in the lab
	Lab                  string   `protobuf:"bytes,1,opt,name=lab,proto3" json:"lab,omitempty"`
	Aisle                string   `protobuf:"bytes,2,opt,name=aisle,proto3" json:"aisle,omitempty"`
	Row                  string   `protobuf:"bytes,3,opt,name=row,proto3" json:"row,omitempty"`
	Rack                 string   `protobuf:"bytes,4,opt,name=rack,proto3" json:"rack,omitempty"`
	Shelf                string   `protobuf:"bytes,5,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Position             string   `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Zone                 string   `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbeede6b2764bfe, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLab() string {
	if m != nil {
		return m.Lab
	}
	return ""
}

func (m *Location) GetAisle() string {
	if m != nil {
		return m.Aisle
	}
	return ""
}

func (m *Location) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *Location) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *Location) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

func (m *Location) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Location) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*ChopsAsset)(nil), "fleet.ChopsAsset")
	proto.RegisterType((*Location)(nil), "fleet.Location")
}

func init() {
	proto.RegisterFile("infra/libs/fleet/protos/asset.proto", fileDescriptor_7fbeede6b2764bfe)
}

var fileDescriptor_7fbeede6b2764bfe = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x4f, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x26, 0xdd, 0xed, 0xda, 0x1d, 0x41, 0x65, 0xf0, 0x10, 0x3c, 0x2d, 0xeb, 0x65, 0x41, 0x68,
	0x40, 0x9f, 0x40, 0x3c, 0x09, 0x9e, 0xfa, 0x06, 0xe9, 0x6e, 0xca, 0x06, 0x43, 0xa7, 0x64, 0x02,
	0x05, 0x1f, 0xc6, 0x67, 0x95, 0x4c, 0x6a, 0x6f, 0xdf, 0x3f, 0x33, 0xf0, 0xec, 0xc7, 0x21, 0x5a,
	0x13, 0x7c, 0xcf, 0x66, 0x08, 0xce, 0x25, 0x33, 0x45, 0x4a, 0xc4, 0xc6, 0x32, 0xbb, 0xd4, 0x0a,
	0xc1, 0x5a, 0x9c, 0xe3, 0x27, 0xc0, 0xc7, 0x95, 0x26, 0x7e, 0xcf, 0x16, 0xde, 0x41, 0xe5, 0x2f,
	0x5a, 0x1d, 0xd4, 0x69, 0xdf, 0x55, 0xfe, 0x82, 0x2f, 0xd0, 0x04, 0x3a, 0xdb, 0xe4, 0x69, 0xd4,
	0xd5, 0x41, 0x9d, 0x6e, 0x5f, 0xef, 0x5b, 0xe9, 0xb5, 0x5f, 0x8b, 0xdc, 0xad, 0x81, 0xe3, 0xaf,
	0x82, 0xe6, 0x5f, 0xc6, 0x07, 0xd8, 0x04, 0xdb, 0x2f, 0x53, 0x19, 0xe2, 0x23, 0xd4, 0xd6, 0x73,
	0x70, 0x32, 0xb4, 0xef, 0x0a, 0xc9, 0xb9, 0x48, 0xb3, 0xde, 0x94, 0x5c, 0xa4, 0x19, 0x11, 0xb6,
	0xd1, 0x9e, 0xbf, 0xf5, 0x56, 0x24, 0xc1, 0xb9, 0xcb, 0x57, 0x17, 0x06, 0x5d, 0x97, 0xae, 0x10,
	0x7c, 0x82, 0x66, 0x22, 0xf6, 0x72, 0xdd, 0x4e, 0x8c, 0x95, 0xe7, 0x95, 0x1f, 0x1a, 0x9d, 0xbe,
	0x29, 0x2b, 0x19, 0xf7, 0x3b, 0xf9, 0xfc, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x24, 0xdd, 0x01,
	0x83, 0x20, 0x01, 0x00, 0x00,
}
