{
  "api_version": 1,
  "automatic_scaling": {
    "max_pending_latency": "0.2s",
    "min_idle_instances": "5"
  },
  "env_variables": {
    "GAE_USE_SOCKETS_HTTPLIB": ""
  },
  "handlers": [
    {
      "login": "admin",
      "script": "monorailapp.app",
      "url": "/_ah/warmup"
    },
    {
      "script": "monorailapp.app",
      "url": "/_backend/.*"
    },
    {
      "login": "admin",
      "script": "monorailapp.app",
      "url": "/_ah/start"
    },
    {
      "login": "admin",
      "script": "monorailapp.app",
      "url": "/_ah/stop"
    }
  ],
  "inbound_services": [
    "warmup"
  ],
  "instance_class": "F4",
  "libraries": [
    {
      "name": "endpoints",
      "version": "1.0"
    },
    {
      "name": "grpcio",
      "version": "1.0.0"
    },
    {
      "name": "MySQLdb",
      "version": "latest"
    },
    {
      "name": "ssl",
      "version": "latest"
    }
  ],
  "runtime": "python27",
  "service": "besearch",
  "skip_files": [
    "^(.*/)?#.*#$",
    "^(.*/)?.*~$",
    "^(.*/)?.*\\.py[co]$",
    "^(.*/)?.*/RCS/.*$",
    "^(.*/)?\\..*$",
    "node_modules/",
    "venv/"
  ],
  "threadsafe": false,
  "vpc_access_connector": {
    "name": "projects/monorail-staging/locations/us-central1/connectors/redis-connector"
  }
}