runtime: python39

inbound_services:
- warmup

handlers:
- url: /node_modules/(.*\.(html|js|css|js))
  static_files: node_modules/\1
  upload: node_modules/(.*\.(html|js|css|js))

- url: /(.*\.(html|js|txt|ttf))
  static_files: static/\1
  upload: static/(.*\.(html|js|txt|ttf))

# main will look for a replacement in blobstore, if not, will redirect to
# static/
- url: /([^/]+\.(gif|png|jpg|ico))
  script: auto  

- url: /static/([^/]+\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/([^/]+\.(gif|png|jpg|ico))

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: auto
